# Generated by Django 5.2.7 on 2025-10-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_facial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
